# ==========================================
# EVERFOREST (KITTY)
# ==========================================

font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.8
dynamic_background_opacity  yes

background            #2b3339
foreground            #d3c6aa
selection_background  #e7dabe
selection_foreground  #2b3339

cursor                #a7c080
cursor_text_color     #2b3339
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background   #a7c080
active_tab_foreground   #2b3339
inactive_tab_background #2b3339
inactive_tab_foreground #d3c6aa

color0  #2b3339
color8  #424a50

color1  #7fbbb3
color9  #e67e80

color2  #83c092
color10 #83c092

color3  #dbbc7f
color11 #e69875

color4  #a7c080
color12 #a7c080

color5  #d699b6
color13 #d699b6

color6  #e69875
color14 #7fbbb3

color7  #d3c6aa
color15 #e7dabe
