# ==========================================
# TOKYONIGHT (KITTY)
# ==========================================

font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.8
dynamic_background_opacity  yes

background            #11121d
foreground            #abb2bf
selection_background  #A0A8CD
selection_foreground  #11121d

cursor                #7199ee
cursor_text_color     #11121d
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background   #7199ee
active_tab_foreground   #11121d
inactive_tab_background #11121d
inactive_tab_foreground #abb2bf

color0  #11121d
color8  #282934

color1  #ee6d85
color9  #f3627a

color2  #95c561
color10 #95c561

color3  #dfae67
color11 #7199ee

color4  #7199ee
color12 #7199ee

color5  #a485dd
color13 #a485dd

color6  #a485dd
color14 #a485dd

color7  #abb2bf
color15 #A0A8CD
