[general]
bars = 54
framerate = 60
autosens = 1

[input]
method = pipewire

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
channels = mono

[smoothing]
monstercat = 1
waves = 0
noise_reduction = 0.77
