# ==========================================
# ROSE PINE (KITTY)
# ==========================================

# --- Fonts & Style ---
font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.8
dynamic_background_opacity  yes

# --- Primary Canvas ---
background            #191724
foreground            #E0DEF4
selection_background  #E0DEF4
selection_foreground  #191724

# --- Cursor ---
cursor                #C4A7E7
cursor_text_color     #191724
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #C4A7E7
active_tab_foreground   #191724
inactive_tab_background #191724
inactive_tab_foreground #908CAA

# ==========================================
# Color Palette
# ==========================================

# Black
color0   #191724
color8   #6E6A86

# Red
color1   #EB6F92
color9   #EB6F92

# Green
color2   #31748F
color10  #31748F

# Yellow
color3   #EBBCBA
color11  #F6C177

# Blue
color4   #C4A7E7
color12  #C4A7E7

# Magenta
color5   #F6C177
color13  #F6C177

# Cyan
color6   #9CCFD8
color14  #9CCFD8

# White
color7   #E0DEF4
color15  #FFFFFF
