# ==========================================
# CATPPUCCIN LATTE (KITTY)
# ==========================================

font_family JetBrainsMono Nerd Font
font_size 12.0
window_padding_width 27

background_opacity 0.8
dynamic_background_opacity yes

background #EFF1F5
foreground #4C4F69
selection_background #4C4F69
selection_foreground #EFF1F5

cursor #1E66F5
cursor_text_color #EFF1F5
cursor_shape beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background #1E66F5
active_tab_foreground #EFF1F5
inactive_tab_background #EFF1F5
inactive_tab_foreground #4C4F69

color0  #EFF1F5
color8  #c3c7d3

color1  #E64553
color9  #FE640B

color2  #40A02B
color10 #04A5E5

color3  #DF8E1D
color11 #5C5F77

color4  #1E66F5
color12 #8839EF

color5  #8839EF
color13 #FE640B

color6  #04A5E5
color14 #6C6F85

color7  #4C4F69
color15 #6C6F85
