# ==========================================
# MONOCHROME (KITTY)
# ==========================================

# --- Fonts & Style ---
font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.8
dynamic_background_opacity  yes

# --- Primary Canvas ---
background            #000000
foreground            #bfc5d0
selection_background  #ced4df
selection_foreground  #101010

# --- Cursor ---
cursor                #ced4df
cursor_text_color     #101010
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #ced4df
active_tab_foreground   #101010
inactive_tab_background #101010
inactive_tab_foreground #bfc5d0

# --- Palette ---
color0  #101010
color8  #383838

color1  #eee8d5
color9  #B8B7B1

color2  #7b9198
color10 #859ba2

color3  #859ba2
color11 #DFDFDA

color4  #ced4df
color12 #c7cdd8

color5  #DAD4C3
color13 #ced4df

color6  #DFDFDA
color14 #ced4df

color7  #bfc5d0
color15 #ced4df
