# ==========================================
# DRACULA (KITTY)
# ==========================================

# --- Fonts & Style ---
font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.8
dynamic_background_opacity  yes

# --- Primary Canvas ---
background            #282A36
foreground            #F8F8F2
selection_background  #44475A
selection_foreground  #F8F8F2

# --- Cursor ---
cursor                #BD93F9
cursor_text_color     #282A36
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #BD93F9
active_tab_foreground   #282A36
inactive_tab_background #282A36
inactive_tab_foreground #F8F8F2

# --- Color Palette ---

color0   #282A36
color8   #44475A

color1   #FF5555
color9   #FF6E6E

color2   #50FA7B
color10  #69FF94

color3   #F1FA8C
color11  #FFFFA5

color4   #6272A4
color12  #8BE9FD

color5   #FF79C6
color13  #BD93F9

color6   #8BE9FD
color14  #A4FFFF

color7   #F8F8F2
color15  #FFFFFF
