# ==========================================
# CATPPUCCIN (KITTY)
# ==========================================

font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.5
dynamic_background_opacity  yes

background            #1E1D2D
foreground            #bfc6d4
selection_background  #D9E0EE
selection_foreground  #1E1D2D

cursor                #89B4FA
cursor_text_color     #1E1D2D
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background   #89B4FA
active_tab_foreground   #1E1D2D
inactive_tab_background #1E1D2D
inactive_tab_foreground #bfc6d4

color0  #1E1D2D
color8  #383747

color1  #F38BA8
color9  #F38BA8

color2  #ABE9B3
color10 #ABE9B3

color3  #FAE3B0
color11 #F8BD96

color4  #89B4FA
color12 #89B4FA

color5  #CBA6F7
color13 #CBA6F7

color6  #89DCEB
color14 #89DCEB

color7  #bfc6d4
color15 #D9E0EE
