# ==========================================
# GITHUB LIGHT (KITTY)
# ==========================================

font_family JetBrainsMono Nerd Font
font_size 12.0
window_padding_width 27

background_opacity 0.8
dynamic_background_opacity yes

background #ffffff
foreground #383d42
selection_background #383d42
selection_foreground #ffffff

cursor #005cc5
cursor_text_color #ffffff
cursor_shape beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background #005cc5
active_tab_foreground #ffffff
inactive_tab_background #ffffff
inactive_tab_foreground #383d42

color0  #ffffff
color8  #d7d9db

color1  #DE2C2E
color9  #b93a86

color2  #4c2889
color10 #8263EB

color3  #b08800
color11 #24292e

color4  #005cc5
color12 #5a32a3

color5  #5a32a3
color13 #044289

color6  #8263EB
color14 #2e3338

color7  #383d42
color15 #24292e
