# ==========================================
# SOLARIZED DARK (KITTY)
# ==========================================

font_family JetBrainsMono Nerd Font
font_size 12.0
window_padding_width 27

background_opacity 0.8
dynamic_background_opacity yes

background #002b36
foreground #93a1a1
selection_background #eee8d5
selection_foreground #002b36

cursor #268bd2
cursor_text_color #002b36
cursor_shape beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background #268bd2
active_tab_foreground #002b36
inactive_tab_background #002b36
inactive_tab_foreground #93a1a1

color0  #002b36
color8  #133e49

color1  #dc322f
color9  #cb4b16

color2  #859900
color10 #2aa198

color3  #b58900
color11 #eee8d5

color4  #268bd2
color12 #6c71c4

color5  #6c71c4
color13 #d33682

color6  #2aa198
color14 #fdf6e3

color7  #93a1a1
color15 #fdf6e3
