# ==========================================
# GRUVBOX LIGHT (KITTY)
# ==========================================

font_family JetBrainsMono Nerd Font
font_size 12.0
window_padding_width 27

background_opacity 0.8
dynamic_background_opacity yes

background #F2E5BC
foreground #504945
selection_background #504945
selection_foreground #F2E5BC

cursor #076678
cursor_text_color #F2E5BC
cursor_shape beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4

active_tab_background #076678
active_tab_foreground #F2E5BC
inactive_tab_background #F2E5BC
inactive_tab_foreground #504945

color0  #F2E5BC
color8  #d8cba2

color1  #9d0006
color9  #af3a03

color2  #79740e
color10 #427b58

color3  #b57614
color11 #3c3836

color4  #076678
color12 #8f3f71

color5  #8f3f71
color13 #d65d0e

color6  #427b58
color14 #282828

color7  #504945
color15 #282828
